exp_name: jigsaw_UAH

random_seed: 300
mode: train
n_classes: 3
aux_classes: 100
method: 'jigsaw'

network:
    arch: resnet101

datasets:
    src:
        type: 'jigsaw'
        name: ['UAH']
        batch_size: 8
        num_workers: 4
        limit: false
        cv_split_id : [1, 2]
        bias_whole_image: 0.7
        aux_classes: 100
        img_transform:
            jitter: 0
            random_horiz_flip: 0
            random_resize_crop: 
                size: [222, 222]
                scale: [0.8, 1.0]
        jig_transform:
            tile_random_grayscale: 0
        normalize:
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]

    tar:
        type: 'jigsaw'
        name: 'UAH'
        batch_size: 8
        num_workers: 4
        limit: false
        aux_classes: 100
        cv_split_id : [3, 4]
        bias_whole_image: 0.4
        img_transform:
            jitter: 0
            random_horiz_flip: 0
            random_resize_crop:
                size: [222, 222]
                scale: [0.8, 1.0]
        jig_transform:
            tile_random_grayscale: 0
        normalize:
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]

training:
    resume: ''
    num_print_epoch: 10
    num_epochs: 50
    optimizer:
        name: 'sgd'
        lr: 0.001
        weight_decay: 0.0005
        momentum: 0.9
        nesterov: true
    lr_scheduler:
        name: step
        step_size: 24 # num_epochs * 0.8
    src_aux_weight: 0.7
    tar_aux_weight: 0.7
    tar_entropy_weight: 0.1
    only_non_scrambled: true